add quiz
Shepaa/front-end-pro pull request #6
Opened 2023-07-03 21:59 UTC by Shepaa

2023-07-04 12:26 UTC, volodymyr-kryvoshapov requested changes

2023-07-04 12:26 UTC, volodymyr-kryvoshapov commented on index.js
> +        question.score = 0;
Мутировать первоначальный объект в данном случае это неправильно, потому что программу сложно читать. Получается что у тебя функция ничего не возвращает, а что-то мутирует, что и где, если программа будет чуть больше, разобраться будет очень сложно. Правильно - создать локальную переменную и в нее считать score

2023-07-04 13:40 UTC, Shepaa commented on index.js
> +        question.score = 0;
сделал

2023-07-05 07:09 UTC, volodymyr-kryvoshapov requested changes

2023-07-05 07:09 UTC, volodymyr-kryvoshapov commented on index.js
> +});
```javascript
question.score
```
ты не исправил проблему ты ее перенес на уровень выше.

Правильно:
```javascript
const score = 0;

QUESTIONS.forEach(question => {
    score += checkScore(question.answer, getAnswer(question.question, question.type));
});

alert(score);
```

2023-07-05 07:09 UTC, volodymyr-kryvoshapov commented on index.js
> +}
Внутренность Ф записывается в одну строку через тернарный оператор

2023-08-29 14:49 UTC, merged